name: deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.4
    - name: Deploy
      run: |
        terraform init
        terraform apply -input=false -auto-approve
